packages:
  - apps/*
  - packages/*
  - tooling/*
catalog:
  dotenv: ^17.2.2
  zod: ^4.1.13
  typescript: ^5
  next: ^16.1.1
  "@trpc/server": ^11.7.2
  "@trpc/client": ^11.7.2
  better-auth: ^1.4.9
  eslint: ^9.28.0
  prettier: ^3.5.3
  "@types/node": ^22.13.14
  dotenv-cli: ^8.0.0
  tsx: ^4.19.4
  drizzle-orm: ^0.43.0
  vitest: ^3.1.0
